Upload Files
Whats-Cookin/decentralized_linkedin pull request #4
Opened 2023-07-15 11:55 UTC by AmrNabel

2023-07-17 14:43 UTC, sahdasamier requested changes
there are aproplem in sizes of boxes , it is so big

2023-07-17 14:52 UTC, sahdasamier requested changes

2023-07-17 14:52 UTC, sahdasamier commented on src/UploadFiles/UploadFiles.tsx
> +          <Button
this button, when you hover over it , it being like the background and totally adding so please add hovering color

2023-07-18 08:05 UTC, AmrNabel commented on src/UploadFiles/UploadFiles.tsx
I did

2023-07-18 08:24 UTC, AmrNabel commented on src/UploadFiles/UploadFiles.tsx
> +        <Typography
I don't see any missing button in the component compared to the given design

2023-07-24 18:27 UTC, sahdasamier requested changes
great job Amr, but please adjust the alert message like what I said

2023-07-28 14:52 UTC, sahdasamier approved these changes

2023-07-28 14:52 UTC, merged